//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuZhuChuShou
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oaEntities : DbContext
    {
        public oaEntities()
            : base("name=oaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionInfo> ActionInfoes { get; set; }
        public DbSet<BumenInfoSet> BumenInfoSets { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public DbSet<RoleInfo> RoleInfoes { get; set; }
        public DbSet<T_BiaoJiInfo> T_BiaoJiInfo { get; set; }
        public DbSet<T_BoolItem> T_BoolItem { get; set; }
        public DbSet<T_City> T_City { get; set; }
        public DbSet<T_FGJHtmlData> T_FGJHtmlData { get; set; }
        public DbSet<T_Items> T_Items { get; set; }
        public DbSet<T_province> T_province { get; set; }
        public DbSet<T_QiuZhuQiuGou> T_QiuZhuQiuGou { get; set; }
        public DbSet<T_Quyu> T_Quyu { get; set; }
        public DbSet<T_SaveHtmlData> T_SaveHtmlData { get; set; }
        public DbSet<T_SeeClickPhoto> T_SeeClickPhoto { get; set; }
        public DbSet<T_UserClick> T_UserClick { get; set; }
        public DbSet<T_UserSave> T_UserSave { get; set; }
        public DbSet<T_UserSave_Items> T_UserSave_Items { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<UserInfo_City> UserInfo_City { get; set; }
        public DbSet<T_ChuZhuInfo> T_ChuZhuInfo { get; set; }
        public DbSet<T_YxPerson> T_YxPerson { get; set; }
        public DbSet<T_ZhuaiJiaBak> T_ZhuaiJiaBak { get; set; }
        public DbSet<UserSaveImage> UserSaveImages { get; set; }
        public DbSet<T_UpHerfCity> T_UpHerfCity { get; set; }
        public DbSet<GongGao> GongGaos { get; set; }
        public DbSet<ScrherSAVE> ScrherSAVEs { get; set; }
        public DbSet<SeeQzCz> SeeQzCzs { get; set; }
        public DbSet<TLoginbak> TLoginbaks { get; set; }
    }
}
