//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuZhuChuShou
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeeQzCz
    {
        public long ID { get; set; }
        public short QCItems { get; set; }
        public Nullable<long> ChuZhuID { get; set; }
        public Nullable<long> QiuZhuID { get; set; }
        public int UserID { get; set; }
        public short Del { get; set; }
    
        public virtual T_ChuZhuInfo T_ChuZhuInfo { get; set; }
        public virtual T_QiuZhuQiuGou T_QiuZhuQiuGou { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
