//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuZhuChuShou
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BiaoJiInfo
    {
        public T_BiaoJiInfo()
        {
            this.T_SaveHtmlData = new HashSet<T_SaveHtmlData>();
        }
    
        public int ID { get; set; }
        public int BiaojiItem { get; set; }
        public string BiaojiStr { get; set; }
        public Nullable<short> DelFlag { get; set; }
        public string Colors { get; set; }
        public string str { get; set; }
    
        public virtual ICollection<T_SaveHtmlData> T_SaveHtmlData { get; set; }
    }
}
