//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuZhuChuShou
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserSave
    {
        public T_UserSave()
        {
            this.UserSaveImages = new HashSet<UserSaveImage>();
        }
    
        public long ID { get; set; }
        public string TextName { get; set; }
        public string PresonName { get; set; }
        public string PresonPhoto { get; set; }
        public string Address { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<int> HuxingStrID { get; set; }
        public Nullable<decimal> Mianji { get; set; }
        public string LouCheng { get; set; }
        public Nullable<int> ZhuanxiuStrID { get; set; }
        public Nullable<int> Nianxian { get; set; }
        public string Chaoxiang { get; set; }
        public Nullable<short> delflag { get; set; }
        public Nullable<int> SumMoneyID { get; set; }
        public Nullable<int> MianjiID { get; set; }
        public Nullable<int> HuXingID { get; set; }
        public Nullable<int> BiaoJiID { get; set; }
        public Nullable<System.DateTime> BiaoJiTime { get; set; }
        public int Items { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Bak { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<UserSaveImage> UserSaveImages { get; set; }
    }
}
