//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuZhuChuShou
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YxPerson
    {
        public T_YxPerson()
        {
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public long ID { get; set; }
        public string PersonName { get; set; }
        public string Photo { get; set; }
        public string Addess { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<double> Gender { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<double> DEL { get; set; }
        public Nullable<int> ADDuserID { get; set; }
        public Nullable<System.DateTime> RuzTime { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
