//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuZhuChuShou
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo>();
            this.T_SaveHtmlData = new HashSet<T_SaveHtmlData>();
            this.T_SaveHtmlData1 = new HashSet<T_SaveHtmlData>();
            this.T_SeeClickPhoto = new HashSet<T_SeeClickPhoto>();
            this.T_UserClick = new HashSet<T_UserClick>();
            this.T_UserSave = new HashSet<T_UserSave>();
            this.UserInfo_City = new HashSet<UserInfo_City>();
            this.Departments = new HashSet<Department>();
            this.RoleInfoes = new HashSet<RoleInfo>();
            this.T_YxPerson = new HashSet<T_YxPerson>();
            this.T_ZhuaiJiaBak = new HashSet<T_ZhuaiJiaBak>();
            this.T_ChuZhuInfo = new HashSet<T_ChuZhuInfo>();
            this.T_FGJHtmlData = new HashSet<T_FGJHtmlData>();
            this.T_QiuZhuQiuGou = new HashSet<T_QiuZhuQiuGou>();
            this.T_UpHerfCity = new HashSet<T_UpHerfCity>();
            this.ScrherSAVEs = new HashSet<ScrherSAVE>();
            this.SeeQzCzs = new HashSet<SeeQzCz>();
            this.TLoginbaks = new HashSet<TLoginbak>();
        }
    
        public int ID { get; set; }
        public string UName { get; set; }
        public string UPwd { get; set; }
        public System.DateTime SubTime { get; set; }
        public short DelFlag { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Remark { get; set; }
        public string Sort { get; set; }
        public System.DateTime OverTime { get; set; }
        public Nullable<int> UserXiaoHao { get; set; }
        public Nullable<int> Click { get; set; }
        public Nullable<bool> ThisMastr { get; set; }
        public Nullable<int> MasterID { get; set; }
        public string Login_now { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<decimal> Umoney { get; set; }
        public Nullable<long> YxPersonID { get; set; }
        public string khName { get; set; }
        public string KhPhoto { get; set; }
    
        public virtual ICollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public virtual T_City T_City { get; set; }
        public virtual ICollection<T_SaveHtmlData> T_SaveHtmlData { get; set; }
        public virtual ICollection<T_SaveHtmlData> T_SaveHtmlData1 { get; set; }
        public virtual ICollection<T_SeeClickPhoto> T_SeeClickPhoto { get; set; }
        public virtual ICollection<T_UserClick> T_UserClick { get; set; }
        public virtual ICollection<T_UserSave> T_UserSave { get; set; }
        public virtual ICollection<UserInfo_City> UserInfo_City { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<RoleInfo> RoleInfoes { get; set; }
        public virtual ICollection<T_YxPerson> T_YxPerson { get; set; }
        public virtual T_YxPerson T_YxPerson1 { get; set; }
        public virtual ICollection<T_ZhuaiJiaBak> T_ZhuaiJiaBak { get; set; }
        public virtual ICollection<T_ChuZhuInfo> T_ChuZhuInfo { get; set; }
        public virtual ICollection<T_FGJHtmlData> T_FGJHtmlData { get; set; }
        public virtual ICollection<T_QiuZhuQiuGou> T_QiuZhuQiuGou { get; set; }
        public virtual ICollection<T_UpHerfCity> T_UpHerfCity { get; set; }
        public virtual ICollection<ScrherSAVE> ScrherSAVEs { get; set; }
        public virtual ICollection<SeeQzCz> SeeQzCzs { get; set; }
        public virtual ICollection<TLoginbak> TLoginbaks { get; set; }
    }
}
