//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpData
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_City
    {
        public T_City()
        {
            this.T_FGJHtmlData = new HashSet<T_FGJHtmlData>();
            this.T_Quyu = new HashSet<T_Quyu>();
            this.UserInfo_City = new HashSet<UserInfo_City>();
            this.UserInfoes = new HashSet<UserInfo>();
            this.T_ChuZhuInfo = new HashSet<T_ChuZhuInfo>();
            this.T_QiuZhuQiuGou = new HashSet<T_QiuZhuQiuGou>();
            this.T_UpHerfCity = new HashSet<T_UpHerfCity>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CityItem { get; set; }
        public string City { get; set; }
        public Nullable<short> DelFlag { get; set; }
        public string City_str { get; set; }
        public Nullable<int> province_id { get; set; }
    
        public virtual ICollection<T_FGJHtmlData> T_FGJHtmlData { get; set; }
        public virtual ICollection<T_Quyu> T_Quyu { get; set; }
        public virtual ICollection<UserInfo_City> UserInfo_City { get; set; }
        public virtual T_province T_province { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual ICollection<T_ChuZhuInfo> T_ChuZhuInfo { get; set; }
        public virtual ICollection<T_QiuZhuQiuGou> T_QiuZhuQiuGou { get; set; }
        public virtual ICollection<T_UpHerfCity> T_UpHerfCity { get; set; }
    }
}
