//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpData
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZhuaiJiaBak
    {
        public long ID { get; set; }
        public string BAK { get; set; }
        public short DEL { get; set; }
        public Nullable<long> FGJHTML_id { get; set; }
        public Nullable<int> AddUser { get; set; }
        public Nullable<System.DateTime> ADDtime { get; set; }
    
        public virtual T_FGJHtmlData T_FGJHtmlData { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
